force-app/main/default/objects/Attendance__c/Attendance__c.object-meta.xml
<CustomObject>
    <label>Attendance</label>
    <nameField>
        <displayFormat>ATN={0000}</displayFormat>
        <label>Attendance</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Attendance__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Attendances</relationshipLabel>
    <relationshipName>AttendanceRecords</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Attendance__c/fields/Monthly_Attendance__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Attendance__c</fullName>
    <label>Monthly Attendance</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Attendance__c/fields/Weekly_Attendance__c.field-meta.xml
<CustomField>
    <fullName>Weekly_Attendance__c</fullName>
    <label>Weekly Attendance</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Attendance__c/fields/Yearly_Attendance__c.field-meta.xml
<CustomField>
    <fullName>Yearly_Attendance__c</fullName>
    <label>Yearly Attendance</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Manager__c.field-meta.xml
<CustomField>
    <fullName>Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Manager</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Employees</relationshipLabel>
    <relationshipName>Subordinates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee_Assignment__c/Employee_Assignment__c.object-meta.xml
<CustomObject>
    <label>Employee Assignment</label>
    <nameField>
        <displayFormat>EM-{0000}</displayFormat>
        <label>Employee Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employee Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee_Assignment__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Employee Assignments (Employee)</relationshipLabel>
    <relationshipName>Employee_Assignments1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee_Assignment__c/fields/Employee_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Employee_Assignment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee Assignment</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Employee Assignments</relationshipLabel>
    <relationshipName>Employee_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee_Assignment__c/fields/Manager__c.field-meta.xml
<CustomField>
    <fullName>Manager__c</fullName>
    <deleteConstraint>Cascade</deleteConstraint>
    <label>Manager</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Employee Assignments (Manager)</relationshipLabel>
    <relationshipName>Employee_Assignments3</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/EmployeeService.cls
public with sharing class EmployeeService {
    public static void createAttendanceRecord(List<Employee__c> newRecords){
        if(newRecords.isEmpty()){
            return;
        }
        List<Attendance__c> createdAttendances = new List<Attendance__c>();
        for(Employee__c emp: newRecords){
            Attendance__c newatn = new Attendance__c(
                Employee__c = emp.Id,
            Weekly_Attendance__c = 100,
            Monthly_Attendance__c = 100,
            Yearly_Attendance__c = 100
                );
            createdAttendances.add(newatn);
        }
        if(!createdAttendances.isEmpty()){
            insert createdAttendances;
        }
    }
    public static void updateEmployeeAssignment(List<Employee__c> newRecords, Map<Id, Employee__c> oldMap) {
        if (newRecords.isEmpty()) {
            return;
        }
        
        List<Employee_Assignment__c> newAssignments = new List<Employee_Assignment__c>();List<Employee_Assignment__c> updatedAssignments = new List<Employee_Assignment__c>();
        
        Set<Id> employeeIds = new Set<Id>();
        
        for (Employee__c emp : newRecords) {
            
            Employee__c oldEmp = oldMap.get(emp.Id);
            
            if (emp.Manager__c != oldEmp.Manager__c) {
                
                employeeIds.add(emp.Id);
                
                if (emp.Manager__c != null) {
                    Employee_Assignment__c assignment =
                        new Employee_Assignment__c(
                        Employee__c = emp.Id,
                    Manager__c = emp.Manager__c,
                    Start_Date__c = Date.today()
                        );
                    
                    newAssignments.add(assignment);
                }
            }
        }
        
        for (Employee_Assignment__c assignment : [
        SELECT Id
        FROM Employee_Assignment__c
        WHERE Employee__c IN :employeeIds
        AND End_Date__c = NULL
    ]) {
            assignment.End_Date__c = Date.today();
            updatedAssignments.add(assignment);
        }
        
        if (!newAssignments.isEmpty()) {
            insert newAssignments;
        }
        
        if (!updatedAssignments.isEmpty()) {
            update updatedAssignments;
        }
    }
}